channels:
  - conda-forge
dependencies:
  - appmode
  - python = 3.7
  - pip
  - pip3
  - tensorboard==1.14.0
  - tensorflow==1.14.0
  - tensorflow-estimator==1.14.0
  - scikit-learn==0.21.3
  - openpyxl==2.6.2
  - xlrd==1.2.0
  - pandas==0.25.0
  - Keras==2.2.4
  - Keras-Applications==1.0.8
  - Keras-Preprocessing==1.1.0
  - gensim==3.8.0
  - numpy==1.16.4
  - scipy==1.3.1
